-- NEXORA - Private Messages V1
-- Migration 045
--
-- Goals:
-- - Add direct player-to-player private messages.
-- - Keep all access server-side through service_role RPCs.
-- - Track unread state with read_at on each message.
-- - Validate recipient, trim message text, block self-messaging.
-- - Add a small server-side send rate limit.
--
-- V1 intentionally excludes:
-- - message deletion
-- - attachments
-- - group messages
-- - block lists
-- - moderation/admin tooling
--
-- Apply after 044_activity_center_v1.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS public.player_private_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_player_id bigint NOT NULL
    REFERENCES public.players(id) ON DELETE CASCADE,
  recipient_player_id bigint NOT NULL
    REFERENCES public.players(id) ON DELETE CASCADE,
  message text NOT NULL
    CHECK (char_length(message) BETWEEN 1 AND 500),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  read_at timestamptz,
  CONSTRAINT player_private_messages_not_self
    CHECK (sender_player_id <> recipient_player_id)
);

CREATE INDEX IF NOT EXISTS idx_private_messages_recipient_created
  ON public.player_private_messages(recipient_player_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_private_messages_sender_created
  ON public.player_private_messages(sender_player_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_private_messages_recipient_unread
  ON public.player_private_messages(recipient_player_id, created_at DESC, id DESC)
  WHERE read_at IS NULL;

CREATE OR REPLACE FUNCTION public.nexora_private_messages_snapshot(
  p_player_id bigint,
  p_limit integer DEFAULT 30
)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_limit integer := LEAST(50, GREATEST(1, COALESCE(p_limit, 30)));
  v_unread_count bigint := 0;
  v_inbox jsonb := '[]'::jsonb;
  v_sent jsonb := '[]'::jsonb;
BEGIN
  IF p_player_id IS NULL
     OR p_player_id <= 0
     OR NOT EXISTS (
       SELECT 1
       FROM public.players p
       WHERE p.id = p_player_id
     ) THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'PLAYER_NOT_FOUND',
      'message', 'Oyuncu bulunamadı.'
    );
  END IF;

  SELECT COUNT(*)::bigint
    INTO v_unread_count
  FROM public.player_private_messages m
  WHERE m.recipient_player_id = p_player_id
    AND m.read_at IS NULL;

  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', x.id,
        'senderPlayerId', x.sender_player_id,
        'senderUsername', x.sender_username,
        'message', x.message,
        'createdAt', x.created_at,
        'readAt', x.read_at,
        'unread', x.read_at IS NULL
      )
      ORDER BY x.created_at DESC, x.id DESC
    ),
    '[]'::jsonb
  )
  INTO v_inbox
  FROM (
    SELECT
      m.id,
      m.sender_player_id,
      p.username AS sender_username,
      m.message,
      m.created_at,
      m.read_at
    FROM public.player_private_messages m
    JOIN public.players p
      ON p.id = m.sender_player_id
    WHERE m.recipient_player_id = p_player_id
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT v_limit
  ) x;

  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', x.id,
        'recipientPlayerId', x.recipient_player_id,
        'recipientUsername', x.recipient_username,
        'message', x.message,
        'createdAt', x.created_at,
        'readAt', x.read_at,
        'read', x.read_at IS NOT NULL
      )
      ORDER BY x.created_at DESC, x.id DESC
    ),
    '[]'::jsonb
  )
  INTO v_sent
  FROM (
    SELECT
      m.id,
      m.recipient_player_id,
      p.username AS recipient_username,
      m.message,
      m.created_at,
      m.read_at
    FROM public.player_private_messages m
    JOIN public.players p
      ON p.id = m.recipient_player_id
    WHERE m.sender_player_id = p_player_id
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT v_limit
  ) x;

  RETURN jsonb_build_object(
    'success', true,
    'serverTime', clock_timestamp(),
    'unreadCount', GREATEST(COALESCE(v_unread_count, 0), 0),
    'inbox', v_inbox,
    'sent', v_sent
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.nexora_send_private_message(
  p_sender_player_id bigint,
  p_recipient_username text,
  p_message text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_sender public.players%ROWTYPE;
  v_recipient public.players%ROWTYPE;
  v_recipient_username text := btrim(COALESCE(p_recipient_username, ''));
  v_message text := btrim(COALESCE(p_message, ''));
  v_message_id bigint;
  v_created_at timestamptz;
BEGIN
  IF p_sender_player_id IS NULL OR p_sender_player_id <= 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'PLAYER_NOT_FOUND',
      'message', 'Oyuncu bulunamadı.'
    );
  END IF;

  SELECT *
    INTO v_sender
  FROM public.players p
  WHERE p.id = p_sender_player_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'PLAYER_NOT_FOUND',
      'message', 'Oyuncu bulunamadı.'
    );
  END IF;

  IF v_recipient_username = '' THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'RECIPIENT_REQUIRED',
      'message', 'Alıcı oyuncu adı gerekli.'
    );
  END IF;

  SELECT *
    INTO v_recipient
  FROM public.players p
  WHERE p.username = v_recipient_username;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'RECIPIENT_NOT_FOUND',
      'message', 'Alıcı oyuncu bulunamadı.'
    );
  END IF;

  IF v_recipient.id = v_sender.id THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'CANNOT_MESSAGE_SELF',
      'message', 'Kendine özel mesaj gönderemezsin.'
    );
  END IF;

  IF v_message = '' THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'MESSAGE_REQUIRED',
      'message', 'Mesaj boş olamaz.'
    );
  END IF;

  IF char_length(v_message) > 500 THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'MESSAGE_TOO_LONG',
      'message', 'Mesaj en fazla 500 karakter olabilir.'
    );
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.player_private_messages m
    WHERE m.sender_player_id = v_sender.id
      AND m.created_at > clock_timestamp() - interval '2 seconds'
  ) THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'MESSAGE_RATE_LIMIT',
      'message', 'Yeni mesaj göndermeden önce kısa bir süre bekle.'
    );
  END IF;

  INSERT INTO public.player_private_messages (
    sender_player_id,
    recipient_player_id,
    message
  )
  VALUES (
    v_sender.id,
    v_recipient.id,
    v_message
  )
  RETURNING id, created_at
    INTO v_message_id, v_created_at;

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Mesaj gönderildi.',
    'item', jsonb_build_object(
      'id', v_message_id,
      'recipientPlayerId', v_recipient.id,
      'recipientUsername', v_recipient.username,
      'message', v_message,
      'createdAt', v_created_at,
      'readAt', NULL,
      'read', false
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.nexora_mark_private_messages_read(
  p_player_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_read_at timestamptz;
BEGIN
  IF p_player_id IS NULL
     OR p_player_id <= 0
     OR NOT EXISTS (
       SELECT 1
       FROM public.players p
       WHERE p.id = p_player_id
     ) THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'PLAYER_NOT_FOUND',
      'message', 'Oyuncu bulunamadı.'
    );
  END IF;

  v_read_at := clock_timestamp();

  UPDATE public.player_private_messages m
  SET read_at = v_read_at
  WHERE m.recipient_player_id = p_player_id
    AND m.read_at IS NULL;

  RETURN public.nexora_private_messages_snapshot(p_player_id, 30);
END;
$function$;

ALTER TABLE public.player_private_messages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.player_private_messages
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.player_private_messages
  TO service_role;

REVOKE ALL ON FUNCTION public.nexora_private_messages_snapshot(bigint, integer)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nexora_send_private_message(bigint, text, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nexora_mark_private_messages_read(bigint)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.nexora_private_messages_snapshot(bigint, integer)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.nexora_send_private_message(bigint, text, text)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.nexora_mark_private_messages_read(bigint)
  TO service_role;

COMMIT;
