-- NEXORA - Alliance Progression V2
-- Migration 059
--
-- Adds durable alliance XP, levels and milestone rewards without changing
-- existing alliance membership, wars, territories or weekly mission behavior.
--
-- XP sources (server-authoritative and non-spammable):
-- - First weekly Alliance Mission chest claim for an alliance/week: +250 XP
-- - Each won Alliance War battle/round: +40 XP
-- - Each finished Alliance War victory: +150 XP
-- - Each territory_claimed alliance activity event: +200 XP
--
-- Level thresholds:
-- 1: 0
-- 2: 100
-- 3: 250
-- 4: 500
-- 5: 900
-- 6: 1400
-- 7: 2000
-- 8: 2800
-- 9: 3800
-- 10: 5000
--
-- Milestone rewards are claimable once per eligible member and level.
-- A member is eligible only if their current membership joined_at is at or
-- before the milestone reached_at timestamp. This prevents joining a mature
-- alliance solely to collect historical level rewards.
--
-- Apply after 058_boss_rewards_trophy_history_v2.sql.
-- Backend/frontend integration is intentionally NOT part of this migration.

BEGIN;

-- -----------------------------------------------------------------------------
-- 1) LEVEL DEFINITIONS
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.game_alliance_levels (
  level integer PRIMARY KEY
    CHECK (level BETWEEN 1 AND 10),
  xp_required bigint NOT NULL
    CHECK (xp_required >= 0),
  title text NOT NULL,
  reward jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(reward) = 'object'),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

INSERT INTO public.game_alliance_levels(
  level,
  xp_required,
  title,
  reward
)
VALUES
  (1, 0,    'Kuruluş',         '{}'::jsonb),
  (2, 100,  'Birlik',          '{"metal":300,"energy":150,"water":300,"crystal":50}'::jsonb),
  (3, 250,  'Dayanışma',       '{"metal":500,"energy":250,"water":500,"crystal":75}'::jsonb),
  (4, 500,  'Güç Birliği',     '{"metal":700,"energy":350,"water":700,"crystal":100}'::jsonb),
  (5, 900,  'Bölgesel Güç',    '{"metal":1000,"energy":500,"water":1000,"crystal":150}'::jsonb),
  (6, 1400, 'Savaş Konseyi',   '{"metal":1300,"energy":650,"water":1300,"crystal":200}'::jsonb),
  (7, 2000, 'Yıldız Birliği',  '{"metal":1600,"energy":800,"water":1600,"crystal":250}'::jsonb),
  (8, 2800, 'Galaktik Güç',    '{"metal":2000,"energy":1000,"water":2000,"crystal":300}'::jsonb),
  (9, 3800, 'İmparatorluk',    '{"metal":2500,"energy":1200,"water":2500,"crystal":400}'::jsonb),
  (10,5000, 'Efsanevi İttifak','{"metal":3200,"energy":1600,"water":3200,"crystal":500}'::jsonb)
ON CONFLICT (level) DO UPDATE SET
  xp_required = EXCLUDED.xp_required,
  title = EXCLUDED.title,
  reward = EXCLUDED.reward;

-- -----------------------------------------------------------------------------
-- 2) DURABLE XP EVENTS + MATERIALIZED PROGRESSION STATE
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.alliance_xp_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alliance_id bigint NOT NULL
    REFERENCES public.alliances(id) ON DELETE CASCADE,
  source_type text NOT NULL
    CHECK (
      source_type IN (
        'mission_week',
        'war_battle_win',
        'war_win',
        'territory_claim'
      )
    ),
  source_key text NOT NULL,
  xp_amount bigint NOT NULL
    CHECK (xp_amount > 0),
  occurred_at timestamptz NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (alliance_id, source_type, source_key)
);

CREATE INDEX IF NOT EXISTS idx_alliance_xp_events_alliance_time
  ON public.alliance_xp_events(
    alliance_id,
    occurred_at,
    id
  );

CREATE TABLE IF NOT EXISTS public.alliance_progression (
  alliance_id bigint PRIMARY KEY
    REFERENCES public.alliances(id) ON DELETE CASCADE,
  total_xp bigint NOT NULL DEFAULT 0
    CHECK (total_xp >= 0),
  level integer NOT NULL DEFAULT 1
    CHECK (level BETWEEN 1 AND 10),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS public.alliance_level_milestones (
  alliance_id bigint NOT NULL
    REFERENCES public.alliances(id) ON DELETE CASCADE,
  level integer NOT NULL
    REFERENCES public.game_alliance_levels(level) ON DELETE RESTRICT,
  reached_at timestamptz NOT NULL,
  total_xp_at_reach bigint NOT NULL
    CHECK (total_xp_at_reach >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (alliance_id, level)
);

CREATE TABLE IF NOT EXISTS public.player_alliance_level_reward_claims (
  player_id bigint NOT NULL
    REFERENCES public.players(id) ON DELETE CASCADE,
  alliance_id bigint NOT NULL
    REFERENCES public.alliances(id) ON DELETE CASCADE,
  level integer NOT NULL
    REFERENCES public.game_alliance_levels(level) ON DELETE RESTRICT,
  configured_reward jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(configured_reward) = 'object'),
  reward jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(reward) = 'object'),
  claimed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (player_id, alliance_id, level)
);

CREATE INDEX IF NOT EXISTS idx_alliance_level_reward_claims_alliance_level
  ON public.player_alliance_level_reward_claims(
    alliance_id,
    level,
    claimed_at
  );

ALTER TABLE public.game_alliance_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alliance_xp_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alliance_progression ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alliance_level_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_alliance_level_reward_claims ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- 3) PROGRESSION REBUILD
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.nexora_rebuild_alliance_progression(
  p_alliance_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_total_xp bigint := 0;
  v_level integer := 1;
  v_level_row record;
  v_reached_at timestamptz;
  v_xp_at_reach bigint;
BEGIN
  IF p_alliance_id IS NULL OR p_alliance_id <= 0 THEN
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1
      FROM public.alliances a
     WHERE a.id = p_alliance_id
  ) THEN
    RETURN;
  END IF;

  SELECT COALESCE(SUM(e.xp_amount), 0)::bigint
    INTO v_total_xp
    FROM public.alliance_xp_events e
   WHERE e.alliance_id = p_alliance_id;

  SELECT COALESCE(MAX(l.level), 1)
    INTO v_level
    FROM public.game_alliance_levels l
   WHERE l.xp_required <= v_total_xp;

  INSERT INTO public.alliance_progression(
    alliance_id,
    total_xp,
    level,
    updated_at
  )
  VALUES(
    p_alliance_id,
    v_total_xp,
    v_level,
    clock_timestamp()
  )
  ON CONFLICT (alliance_id) DO UPDATE SET
    total_xp = EXCLUDED.total_xp,
    level = EXCLUDED.level,
    updated_at = EXCLUDED.updated_at;

  FOR v_level_row IN
    SELECT l.level, l.xp_required
      FROM public.game_alliance_levels l
     WHERE l.level >= 2
       AND l.xp_required <= v_total_xp
     ORDER BY l.level
  LOOP
    SELECT x.occurred_at, x.running_xp
      INTO v_reached_at, v_xp_at_reach
      FROM (
        SELECT
          e.occurred_at,
          e.id,
          SUM(e.xp_amount) OVER (
            ORDER BY e.occurred_at, e.id
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
          )::bigint AS running_xp
        FROM public.alliance_xp_events e
        WHERE e.alliance_id = p_alliance_id
      ) x
     WHERE x.running_xp >= v_level_row.xp_required
     ORDER BY x.occurred_at, x.id
     LIMIT 1;

    IF v_reached_at IS NOT NULL THEN
      INSERT INTO public.alliance_level_milestones(
        alliance_id,
        level,
        reached_at,
        total_xp_at_reach,
        created_at
      )
      VALUES(
        p_alliance_id,
        v_level_row.level,
        v_reached_at,
        v_xp_at_reach,
        clock_timestamp()
      )
      ON CONFLICT (alliance_id, level) DO UPDATE SET
        reached_at = EXCLUDED.reached_at,
        total_xp_at_reach = EXCLUDED.total_xp_at_reach;
    END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.nexora_add_alliance_xp_event(
  p_alliance_id bigint,
  p_source_type text,
  p_source_key text,
  p_xp_amount bigint,
  p_occurred_at timestamptz,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_inserted boolean := false;
BEGIN
  IF p_alliance_id IS NULL
     OR p_alliance_id <= 0
     OR p_source_type IS NULL
     OR p_source_type NOT IN (
       'mission_week',
       'war_battle_win',
       'war_win',
       'territory_claim'
     )
     OR p_source_key IS NULL
     OR btrim(p_source_key) = ''
     OR p_xp_amount IS NULL
     OR p_xp_amount <= 0
     OR p_occurred_at IS NULL
     OR p_metadata IS NULL
     OR jsonb_typeof(p_metadata) IS DISTINCT FROM 'object' THEN
    RETURN false;
  END IF;

  INSERT INTO public.alliance_xp_events(
    alliance_id,
    source_type,
    source_key,
    xp_amount,
    occurred_at,
    metadata,
    created_at
  )
  VALUES(
    p_alliance_id,
    p_source_type,
    p_source_key,
    p_xp_amount,
    p_occurred_at,
    p_metadata,
    clock_timestamp()
  )
  ON CONFLICT (alliance_id, source_type, source_key) DO NOTHING;

  v_inserted := FOUND;

  IF v_inserted THEN
    PERFORM public.nexora_rebuild_alliance_progression(p_alliance_id);
  END IF;

  RETURN v_inserted;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 4) BACKFILL EXISTING AUTHORITATIVE HISTORY
-- -----------------------------------------------------------------------------

-- Weekly alliance mission completion: one XP event per alliance/week, regardless
-- of how many members claimed the shared chest.
INSERT INTO public.alliance_xp_events(
  alliance_id,
  source_type,
  source_key,
  xp_amount,
  occurred_at,
  metadata
)
SELECT
  c.alliance_id,
  'mission_week',
  c.week_start::text,
  250,
  MIN(c.claimed_at),
  jsonb_build_object('weekStart', c.week_start)
FROM public.player_alliance_mission_chest_claims c
GROUP BY c.alliance_id, c.week_start
ON CONFLICT (alliance_id, source_type, source_key) DO NOTHING;

-- Won war battle/round.
INSERT INTO public.alliance_xp_events(
  alliance_id,
  source_type,
  source_key,
  xp_amount,
  occurred_at,
  metadata
)
SELECT
  b.winner_alliance_id,
  'war_battle_win',
  b.id::text,
  40,
  b.battle_at,
  jsonb_build_object(
    'warId', b.war_id,
    'battleId', b.id,
    'points', b.points
  )
FROM public.alliance_war_battles b
WHERE b.winner_alliance_id IS NOT NULL
ON CONFLICT (alliance_id, source_type, source_key) DO NOTHING;

-- Finished alliance war victory.
INSERT INTO public.alliance_xp_events(
  alliance_id,
  source_type,
  source_key,
  xp_amount,
  occurred_at,
  metadata
)
SELECT
  w.winner_alliance_id,
  'war_win',
  w.id::text,
  150,
  COALESCE(w.finished_at, w.ends_at, w.started_at, w.created_at),
  jsonb_build_object(
    'warId', w.id,
    'challengerScore', w.challenger_score,
    'targetScore', w.target_score
  )
FROM public.alliance_wars w
WHERE w.status = 'finished'
  AND w.winner_alliance_id IS NOT NULL
ON CONFLICT (alliance_id, source_type, source_key) DO NOTHING;

-- Territory claims are stored as immutable alliance activity events.
INSERT INTO public.alliance_xp_events(
  alliance_id,
  source_type,
  source_key,
  xp_amount,
  occurred_at,
  metadata
)
SELECT
  aa.alliance_id,
  'territory_claim',
  aa.id::text,
  200,
  aa.created_at,
  jsonb_build_object(
    'activityId', aa.id,
    'metadata', COALESCE(aa.metadata, '{}'::jsonb)
  )
FROM public.alliance_activity aa
WHERE aa.event_type = 'territory_claimed'
ON CONFLICT (alliance_id, source_type, source_key) DO NOTHING;

-- Rebuild every current alliance after backfill.
DO $block$
DECLARE
  v_alliance record;
BEGIN
  FOR v_alliance IN
    SELECT a.id
      FROM public.alliances a
     ORDER BY a.id
  LOOP
    PERFORM public.nexora_rebuild_alliance_progression(v_alliance.id);
  END LOOP;
END;
$block$;

-- -----------------------------------------------------------------------------
-- 5) FUTURE XP TRACKING TRIGGERS
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.nexora_track_alliance_mission_xp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $function$
BEGIN
  PERFORM public.nexora_add_alliance_xp_event(
    NEW.alliance_id,
    'mission_week',
    NEW.week_start::text,
    250,
    NEW.claimed_at,
    jsonb_build_object('weekStart', NEW.week_start)
  );
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_nexora_alliance_mission_xp
  ON public.player_alliance_mission_chest_claims;

CREATE TRIGGER trg_nexora_alliance_mission_xp
AFTER INSERT ON public.player_alliance_mission_chest_claims
FOR EACH ROW
EXECUTE FUNCTION public.nexora_track_alliance_mission_xp();

CREATE OR REPLACE FUNCTION public.nexora_track_alliance_war_battle_xp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $function$
BEGIN
  IF NEW.winner_alliance_id IS NOT NULL THEN
    PERFORM public.nexora_add_alliance_xp_event(
      NEW.winner_alliance_id,
      'war_battle_win',
      NEW.id::text,
      40,
      NEW.battle_at,
      jsonb_build_object(
        'warId', NEW.war_id,
        'battleId', NEW.id,
        'points', NEW.points
      )
    );
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_nexora_alliance_war_battle_xp
  ON public.alliance_war_battles;

CREATE TRIGGER trg_nexora_alliance_war_battle_xp
AFTER INSERT ON public.alliance_war_battles
FOR EACH ROW
EXECUTE FUNCTION public.nexora_track_alliance_war_battle_xp();

CREATE OR REPLACE FUNCTION public.nexora_track_alliance_war_win_xp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $function$
BEGIN
  IF NEW.status = 'finished'
     AND NEW.winner_alliance_id IS NOT NULL
     AND (
       TG_OP = 'INSERT'
       OR OLD.status IS DISTINCT FROM NEW.status
       OR OLD.winner_alliance_id IS DISTINCT FROM NEW.winner_alliance_id
     ) THEN
    PERFORM public.nexora_add_alliance_xp_event(
      NEW.winner_alliance_id,
      'war_win',
      NEW.id::text,
      150,
      COALESCE(
        NEW.finished_at,
        NEW.ends_at,
        NEW.started_at,
        NEW.created_at
      ),
      jsonb_build_object(
        'warId', NEW.id,
        'challengerScore', NEW.challenger_score,
        'targetScore', NEW.target_score
      )
    );
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_nexora_alliance_war_win_xp
  ON public.alliance_wars;

CREATE TRIGGER trg_nexora_alliance_war_win_xp
AFTER INSERT OR UPDATE OF
  status,
  winner_alliance_id,
  finished_at,
  challenger_score,
  target_score
ON public.alliance_wars
FOR EACH ROW
EXECUTE FUNCTION public.nexora_track_alliance_war_win_xp();

CREATE OR REPLACE FUNCTION public.nexora_track_alliance_territory_xp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $function$
BEGIN
  IF NEW.event_type = 'territory_claimed' THEN
    PERFORM public.nexora_add_alliance_xp_event(
      NEW.alliance_id,
      'territory_claim',
      NEW.id::text,
      200,
      NEW.created_at,
      jsonb_build_object(
        'activityId', NEW.id,
        'metadata', COALESCE(NEW.metadata, '{}'::jsonb)
      )
    );
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_nexora_alliance_territory_xp
  ON public.alliance_activity;

CREATE TRIGGER trg_nexora_alliance_territory_xp
AFTER INSERT ON public.alliance_activity
FOR EACH ROW
EXECUTE FUNCTION public.nexora_track_alliance_territory_xp();

-- -----------------------------------------------------------------------------
-- 6) READ-ONLY SNAPSHOT
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.nexora_alliance_progression_snapshot(
  p_player_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_member public.alliance_members%ROWTYPE;
  v_alliance public.alliances%ROWTYPE;
  v_progress public.alliance_progression%ROWTYPE;
  v_current public.game_alliance_levels%ROWTYPE;
  v_next public.game_alliance_levels%ROWTYPE;
  v_levels jsonb := '[]'::jsonb;
  v_xp_sources jsonb := '{}'::jsonb;
  v_recent_xp jsonb := '[]'::jsonb;
BEGIN
  IF p_player_id IS NULL OR p_player_id <= 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'INVALID_PLAYER',
      'message', 'Geçersiz oyuncu.'
    );
  END IF;

  SELECT am.*
    INTO v_member
    FROM public.alliance_members am
   WHERE am.player_id = p_player_id
   LIMIT 1;

  IF v_member.id IS NULL THEN
    RETURN jsonb_build_object(
      'success', true,
      'inAlliance', false,
      'levels', '[]'::jsonb,
      'recentXp', '[]'::jsonb
    );
  END IF;

  SELECT a.*
    INTO v_alliance
    FROM public.alliances a
   WHERE a.id = v_member.alliance_id;

  SELECT ap.*
    INTO v_progress
    FROM public.alliance_progression ap
   WHERE ap.alliance_id = v_member.alliance_id;

  IF v_progress.alliance_id IS NULL THEN
    v_progress.alliance_id := v_member.alliance_id;
    v_progress.total_xp := 0;
    v_progress.level := 1;
  END IF;

  SELECT l.*
    INTO v_current
    FROM public.game_alliance_levels l
   WHERE l.level = v_progress.level;

  SELECT l.*
    INTO v_next
    FROM public.game_alliance_levels l
   WHERE l.level = v_progress.level + 1;

  SELECT COALESCE(
           jsonb_object_agg(x.source_type, x.xp),
           '{}'::jsonb
         )
    INTO v_xp_sources
    FROM (
      SELECT
        e.source_type,
        SUM(e.xp_amount)::bigint AS xp
      FROM public.alliance_xp_events e
      WHERE e.alliance_id = v_member.alliance_id
      GROUP BY e.source_type
    ) x;

  SELECT COALESCE(
           jsonb_agg(
             jsonb_build_object(
               'level', l.level,
               'title', l.title,
               'xpRequired', l.xp_required,
               'reward', l.reward,
               'reached', m.level IS NOT NULL,
               'reachedAt', m.reached_at,
               'eligible',
                 m.level IS NOT NULL
                 AND v_member.joined_at <= m.reached_at,
               'claimed', claim.level IS NOT NULL,
               'claimedAt', claim.claimed_at,
               'creditedReward',
                 COALESCE(claim.reward, '{}'::jsonb),
               'claimable',
                 m.level IS NOT NULL
                 AND v_member.joined_at <= m.reached_at
                 AND claim.level IS NULL
                 AND l.level >= 2
             )
             ORDER BY l.level
           ),
           '[]'::jsonb
         )
    INTO v_levels
    FROM public.game_alliance_levels l
    LEFT JOIN public.alliance_level_milestones m
      ON m.alliance_id = v_member.alliance_id
     AND m.level = l.level
    LEFT JOIN public.player_alliance_level_reward_claims claim
      ON claim.player_id = p_player_id
     AND claim.alliance_id = v_member.alliance_id
     AND claim.level = l.level;

  SELECT COALESCE(
           jsonb_agg(
             jsonb_build_object(
               'sourceType', x.source_type,
               'xp', x.xp_amount,
               'occurredAt', x.occurred_at,
               'metadata', x.metadata
             )
             ORDER BY x.occurred_at DESC, x.id DESC
           ),
           '[]'::jsonb
         )
    INTO v_recent_xp
    FROM (
      SELECT e.*
        FROM public.alliance_xp_events e
       WHERE e.alliance_id = v_member.alliance_id
       ORDER BY e.occurred_at DESC, e.id DESC
       LIMIT 10
    ) x;

  RETURN jsonb_build_object(
    'success', true,
    'inAlliance', true,
    'alliance', jsonb_build_object(
      'id', v_alliance.id,
      'name', v_alliance.name,
      'tag', v_alliance.tag
    ),
    'member', jsonb_build_object(
      'playerId', v_member.player_id,
      'joinedAt', v_member.joined_at,
      'role',
        CASE
          WHEN v_member.role = 'leader' THEN 'leader'
          WHEN v_member.role_v2 = 'officer' THEN 'officer'
          ELSE 'member'
        END
    ),
    'progression', jsonb_build_object(
      'level', v_progress.level,
      'title', COALESCE(v_current.title, 'Kuruluş'),
      'totalXp', v_progress.total_xp,
      'currentLevelXp', COALESCE(v_current.xp_required, 0),
      'nextLevel', v_next.level,
      'nextTitle', v_next.title,
      'nextLevelXp', v_next.xp_required,
      'xpIntoLevel',
        GREATEST(
          0,
          v_progress.total_xp - COALESCE(v_current.xp_required, 0)
        ),
      'xpNeededForNext',
        CASE
          WHEN v_next.level IS NULL THEN 0
          ELSE GREATEST(
            0,
            v_next.xp_required - v_progress.total_xp
          )
        END,
      'maxLevel', v_next.level IS NULL
    ),
    'xpSources', v_xp_sources,
    'levels', v_levels,
    'recentXp', v_recent_xp
  );
END;
$function$;

-- -----------------------------------------------------------------------------
-- 7) MILESTONE REWARD CLAIM
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.nexora_claim_alliance_level_reward(
  p_player_id bigint,
  p_level integer
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_member public.alliance_members%ROWTYPE;
  v_milestone public.alliance_level_milestones%ROWTYPE;
  v_level public.game_alliance_levels%ROWTYPE;
  v_city public.cities%ROWTYPE;
  v_existing jsonb;
  v_configured jsonb;
  v_credited jsonb;
  v_credit_metal bigint := 0;
  v_credit_energy bigint := 0;
  v_credit_water bigint := 0;
  v_credit_crystal bigint := 0;
BEGIN
  IF p_player_id IS NULL
     OR p_player_id <= 0
     OR p_level IS NULL
     OR p_level < 2
     OR p_level > 10 THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'INVALID_INPUT',
      'message', 'Geçersiz ittifak seviye ödülü isteği.'
    );
  END IF;

  PERFORM p.id
    FROM public.players p
   WHERE p.id = p_player_id
   FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'PLAYER_NOT_FOUND',
      'message', 'Oyuncu bulunamadı.'
    );
  END IF;

  SELECT am.*
    INTO v_member
    FROM public.alliance_members am
   WHERE am.player_id = p_player_id
   FOR UPDATE;

  IF v_member.id IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'NOT_IN_ALLIANCE',
      'message', 'Bir ittifaka üye değilsin.'
    );
  END IF;

  SELECT m.*
    INTO v_milestone
    FROM public.alliance_level_milestones m
   WHERE m.alliance_id = v_member.alliance_id
     AND m.level = p_level;

  IF v_milestone.alliance_id IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'LEVEL_NOT_REACHED',
      'message', 'İttifak bu seviyeye henüz ulaşmadı.'
    );
  END IF;

  IF v_member.joined_at > v_milestone.reached_at THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'NOT_ELIGIBLE',
      'message', 'Bu seviye kazanıldığında ittifak üyesi değildin.'
    );
  END IF;

  SELECT l.*
    INTO v_level
    FROM public.game_alliance_levels l
   WHERE l.level = p_level;

  IF v_level.level IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'LEVEL_NOT_FOUND',
      'message', 'İttifak seviyesi bulunamadı.'
    );
  END IF;

  SELECT c.reward
    INTO v_existing
    FROM public.player_alliance_level_reward_claims c
   WHERE c.player_id = p_player_id
     AND c.alliance_id = v_member.alliance_id
     AND c.level = p_level
   LIMIT 1;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'success', true,
      'alreadyClaimed', true,
      'message', 'Bu ittifak seviye ödülünü zaten aldın.',
      'creditedReward', COALESCE(v_existing, '{}'::jsonb),
      'snapshot',
        public.nexora_alliance_progression_snapshot(p_player_id)
    );
  END IF;

  v_configured := v_level.reward;

  IF v_configured IS NULL
     OR jsonb_typeof(v_configured) IS DISTINCT FROM 'object'
     OR EXISTS (
       SELECT 1
         FROM jsonb_each_text(v_configured) r(key, value)
        WHERE key NOT IN ('metal','energy','water','crystal')
           OR value !~ '^[0-9]+$'
           OR char_length(value) > 12
     ) THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'ALLIANCE_LEVEL_REWARD_INVALID',
      'message', 'İttifak seviye ödülü yapılandırması geçersiz.'
    );
  END IF;

  SELECT *
    INTO v_city
    FROM public.cities c
   WHERE c.player_id = p_player_id
   ORDER BY c.id
   LIMIT 1
   FOR UPDATE;

  IF v_city.id IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'code', 'CITY_NOT_FOUND',
      'message', 'Şehir bulunamadı.'
    );
  END IF;

  v_credit_metal :=
    LEAST(
      COALESCE((v_configured->>'metal')::bigint, 0),
      GREATEST(
        COALESCE(v_city.metal_capacity, 0) - COALESCE(v_city.metal, 0),
        0
      )
    );

  v_credit_energy :=
    LEAST(
      COALESCE((v_configured->>'energy')::bigint, 0),
      GREATEST(
        COALESCE(v_city.energy_capacity, 0) - COALESCE(v_city.energy, 0),
        0
      )
    );

  v_credit_water :=
    LEAST(
      COALESCE((v_configured->>'water')::bigint, 0),
      GREATEST(
        COALESCE(v_city.water_capacity, 0) - COALESCE(v_city.water, 0),
        0
      )
    );

  v_credit_crystal :=
    LEAST(
      COALESCE((v_configured->>'crystal')::bigint, 0),
      GREATEST(
        COALESCE(v_city.crystal_capacity, 0) - COALESCE(v_city.crystal, 0),
        0
      )
    );

  v_credited := jsonb_build_object(
    'metal', v_credit_metal,
    'energy', v_credit_energy,
    'water', v_credit_water,
    'crystal', v_credit_crystal
  );

  INSERT INTO public.player_alliance_level_reward_claims(
    player_id,
    alliance_id,
    level,
    configured_reward,
    reward,
    claimed_at
  )
  VALUES(
    p_player_id,
    v_member.alliance_id,
    p_level,
    v_configured,
    v_credited,
    clock_timestamp()
  )
  ON CONFLICT (player_id, alliance_id, level) DO NOTHING;

  IF NOT FOUND THEN
    SELECT c.reward
      INTO v_existing
      FROM public.player_alliance_level_reward_claims c
     WHERE c.player_id = p_player_id
       AND c.alliance_id = v_member.alliance_id
       AND c.level = p_level
     LIMIT 1;

    RETURN jsonb_build_object(
      'success', true,
      'alreadyClaimed', true,
      'message', 'Bu ittifak seviye ödülünü zaten aldın.',
      'creditedReward', COALESCE(v_existing, '{}'::jsonb),
      'snapshot',
        public.nexora_alliance_progression_snapshot(p_player_id)
    );
  END IF;

  UPDATE public.cities
     SET metal = COALESCE(metal, 0) + v_credit_metal,
         energy = COALESCE(energy, 0) + v_credit_energy,
         water = COALESCE(water, 0) + v_credit_water,
         crystal = COALESCE(crystal, 0) + v_credit_crystal,
         updated_at = clock_timestamp()
   WHERE id = v_city.id;

  INSERT INTO public.alliance_activity(
    alliance_id,
    event_type,
    actor_player_id,
    metadata,
    created_at
  )
  VALUES(
    v_member.alliance_id,
    'alliance_level_reward_claimed',
    p_player_id,
    jsonb_build_object(
      'level', p_level,
      'reward', v_credited
    ),
    clock_timestamp()
  );

  RETURN jsonb_build_object(
    'success', true,
    'alreadyClaimed', false,
    'message', 'İttifak seviye ödülü alındı.',
    'configuredReward', v_configured,
    'creditedReward', v_credited,
    'snapshot',
      public.nexora_alliance_progression_snapshot(p_player_id)
  );
END;
$function$;

-- -----------------------------------------------------------------------------
-- 8) SECURITY / EXPLICIT DATA API GRANTS
-- -----------------------------------------------------------------------------

REVOKE ALL ON TABLE public.game_alliance_levels
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.alliance_xp_events
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.alliance_progression
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.alliance_level_milestones
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.player_alliance_level_reward_claims
  FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE public.game_alliance_levels TO service_role;
GRANT SELECT, INSERT ON TABLE public.alliance_xp_events TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.alliance_progression TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE public.alliance_level_milestones TO service_role;
GRANT SELECT, INSERT ON TABLE public.player_alliance_level_reward_claims TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.alliance_xp_events_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.nexora_rebuild_alliance_progression(bigint)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nexora_add_alliance_xp_event(
  bigint, text, text, bigint, timestamptz, jsonb
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nexora_track_alliance_mission_xp()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nexora_track_alliance_war_battle_xp()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nexora_track_alliance_war_win_xp()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nexora_track_alliance_territory_xp()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nexora_alliance_progression_snapshot(bigint)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.nexora_claim_alliance_level_reward(bigint, integer)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.nexora_rebuild_alliance_progression(bigint)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.nexora_add_alliance_xp_event(
  bigint, text, text, bigint, timestamptz, jsonb
) TO service_role;
GRANT EXECUTE ON FUNCTION public.nexora_track_alliance_mission_xp()
  TO service_role;
GRANT EXECUTE ON FUNCTION public.nexora_track_alliance_war_battle_xp()
  TO service_role;
GRANT EXECUTE ON FUNCTION public.nexora_track_alliance_war_win_xp()
  TO service_role;
GRANT EXECUTE ON FUNCTION public.nexora_track_alliance_territory_xp()
  TO service_role;
GRANT EXECUTE ON FUNCTION public.nexora_alliance_progression_snapshot(bigint)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.nexora_claim_alliance_level_reward(bigint, integer)
  TO service_role;

COMMIT;
